language: cpp

sudo: false
dist: trusty

env:
  global:
    - OMP_NUM_THREADS=4
    - GLOBAL_CFLAGS="-std=c++11 -Iinclude -fPIC"

matrix:
  include:
    # - os: linux
    #   env: MY_CXX="g++" OMP_LDFLAGS="-fopenmp" CFLAGS="-O3"
    # - os: linux
    #   env:  MY_CXX="g++" OMP_LDFLAGS="-fopenmp" CFLAGS="-O3 -march=native -ffast-math"
    # - os: linux
    #   env:  MY_CXX="g++" OMP_LDFLAGS="-fopenmp" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG"
    # - os: linux
    #   env:  MY_CXX="g++" OMP_LDFLAGS="-fopenmp" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG -DROUTING_KIT_NO_GCC_EXTENSIONS -DROUTING_KIT_NO_POSIX"
    - os: linux
      addons: &clang5
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libiomp-dev
            - libiomp5
      env: MY_CXX="clang++-5.0" OMP_LDFLAGS="-fopenmp=libiomp5" CFLAGS="-O3"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" OMP_LDFLAGS="-fopenmp=libiomp5" CFLAGS="-O3 -march=native -ffast-math"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" OMP_LDFLAGS="-fopenmp=libiomp5" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" OMP_LDFLAGS="-fopenmp=libiomp5" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG -DROUTING_KIT_NO_GCC_EXTENSIONS -DROUTING_KIT_NO_POSIX"
    - os: linux
      addons: *clang5
      env: MY_CXX="clang++-5.0" OMP_LDFLAGS="-fopenmp=libiomp5" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG -fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-fsanitize=address"

before_script:
  - echo MY_CXX=$MY_CXX
  - echo GLOBAL_CFLAGS=$GLOBAL_CFLAGS
  - echo CFLAGS=CFLAGS
  - echo LDFLAGS=LDFLAGS
  - echo OMP_LDFLAGS=OMP_LDFLAGS
  - $MY_CXX --version
  - make CC="$MY_CXX" CFLAGS="$GLOBAL_CFLAGS $CFLAGS" LDFLAGS="$LDFLAGS" OMP_LDFLAGS="$OMP_LDFLAGS" -j2
  - git clone https://github.com/RoutingKit/DataForAutomaticTests.git data

script:
  - bin/test_bit_vector
  - bin/test_buffered_asynchronous_reader
  - bin/test_geo_dist
  - bin/test_id_mapper
  - bin/test_id_set_queue
  - bin/test_inverse_vector
  - bin/test_nearest_neighbor
  - bin/test_nested_dissection
  - bin/test_permutation
  - bin/test_protobuf
  - bin/test_sort
  - bin/test_tag_map
  - bin/test_dijkstra data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time
  - bin/test_contraction_hierarchy_extra_weight data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time data/tuebingen_geo_distance
  - bin/test_contraction_hierarchy_path_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time data/tuebingen_travel_time_ch data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_travel_time_length
  - bin/test_contraction_hierarchy_path_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_geo_distance data/tuebingen_geo_distance_ch data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_geo_distance_length
  - bin/test_contraction_hierarchy_pinned_query data/tuebingen_travel_time_ch
  - bin/test_contraction_hierarchy_pinned_query data/tuebingen_geo_distance_ch
  - bin/test_customizable_contraction_hierarchy data/tuebingen_first_out data/tuebingen_head data/tuebingen_cch_order
  - bin/test_customizable_contraction_hierarchy_path_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time data/tuebingen_cch_order data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_travel_time_length
  - bin/test_customizable_contraction_hierarchy_path_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_geo_distance data/tuebingen_cch_order data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_geo_distance_length
  - bin/test_customizable_contraction_hierarchy_perfect_customization data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time data/tuebingen_cch_order data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_travel_time_length
  - bin/test_customizable_contraction_hierarchy_perfect_customization data/tuebingen_first_out data/tuebingen_head data/tuebingen_geo_distance data/tuebingen_cch_order data/tuebingen_source_node data/tuebingen_target_node data/tuebingen_query_reference_geo_distance_length
  - bin/test_customizable_contraction_hierarchy_pinned_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_travel_time data/tuebingen_cch_order
  - bin/test_customizable_contraction_hierarchy_pinned_query data/tuebingen_first_out data/tuebingen_head data/tuebingen_geo_distance data/tuebingen_cch_order
  - bin/test_basic_features data/tuebingen.pbf
