language: cpp

sudo: false
dist: trusty

env:
  global:
    - OMP_NUM_THREADS=4
    - GLOBAL_CFLAGS="-std=c++11 -Iinclude -fPIC"

matrix:
  include:
    - os: linux
      env: MY_CXX="g++" CFLAGS="-O3"
    # - os: linux
    #   env:  MY_CXX="g++" CFLAGS="-O3 -march=native -ffast-math"
    # - os: linux
    #   env:  MY_CXX="g++" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG"
    # - os: linux
    #   env:  MY_CXX="g++" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG -DROUTING_KIT_NO_GCC_EXTENSIONS -DROUTING_KIT_NO_POSIX"
    - os: linux
      addons: &clang5
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libompl-dev
      env: MY_CXX="clang++-5.0" CFLAGS="-O3"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" CFLAGS="-O3 -march=native -ffast-math"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG"
    # - os: linux
    #   addons: *clang5
    #   env: MY_CXX="clang++-5.0" CFLAGS="-O3 -march=native -ffast-math -DNDEBUG -DROUTING_KIT_NO_GCC_EXTENSIONS -DROUTING_KIT_NO_POSIX"

before_script:
  - $MY_CXX --version
  - make CC="$MY_CXX" CFLAGS="$GLOBAL_CFLAGS $CFLAGS" -j2
  - wget http://download.geofabrik.de/europe/luxembourg-latest.osm.pbf
  - bin/osm_extract luxembourg-latest.osm.pbf first_out head geo_distance travel_time latitude longitude

script:
  - bin/test_bit_vector
  - bin/test_buffered_asynchronous_reader
  - bin/test_geo_dist
  - bin/test_id_mapper
  - bin/test_id_set_queue
  - bin/test_inverse_vector
  - bin/test_nested_dissection
  - bin/test_permutation
  - bin/test_protobuf
  - bin/test_sort
  - bin/test_tag_map
  - bin/test_basic_features luxembourg-latest.osm.pbf
